### PR TITLE
Fix issues with submitting jobs to Torque

### PR DESCRIPTION
**Pull request by raj76**
The -cwd option does not exist for torque version of qsub. This fixes the issue and makes it work for Torque.

### CODE REVIEW

**Comment by pb-cdunn** [comment]
Thanks, @raj76. I will fix our TravisCI errors and then rebase your change, which did not cause the errors.

**Comment by pb-cdunn** [comment]
Wait. Your solution is wrong, I think. We still need `-o` and `-e`, and we need specify the CWD somehow.

> qsub -d path: Defines the working directory path to be used for the job. If the -d option is not specified, the default working directory is the home directory. This option sets the environment variable PBS_O_INITDIR.

* http://docs.adaptivecomputing.com/torque/4-0-2/help.htm#topics/12-appendices/commandsOverview.htm

I'll push a different change and let you test it, ok?

**Comment by pb-cdunn** [comment]
I pushed a fix to branch `issue-19`. Could you try it? Or at least review the code?

**Comment by raj76** [comment]
@pb-cdunn The issue-19 branch is working fine. The jobs are being submitted to the queue.
The system still can't delete/kill he queued jobs as the job id it used for the qdel is wrong. It is using the job name rather than the jobid.

Thanks,
-Raj

**Comment by pb-cdunn** [comment]
How do we learn the jobid? Must we parse the result of the **qsub** command? If so, could you provide an example for Torque?

**Comment by raj76** [comment]
Yeah, the output of the qsub command contains the jobid. In Torque the jobid can have some extension (i.e. our installation returns 127566.pbs.scm) the .pbs.scm may change depending on the installation. I just use the following regex, /(\d+)(\.[0-9a-zA-Z])*/ to extract the number part.

**Comment by pb-cdunn** [comment]
I'll work on this late next week. If you fix this before I get to it, you can rebase your branch and force-push into your repo. This PR will automatically update.

**Comment by pb-cdunn** [comment]
I think we've got your fix elsewhere now. Please re-open if that's wrong.

**Pull request closed without merging**
